<style>
body {
  background: url("./css/background.jpg") no-repeat;
  background-size: cover;
  margin: 0;
  font-family: Arial;
}

.topnav {
  position: relative;
  overflow: hidden;
  background-color: grey;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 18px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #ddd;
  color: black;
}

.topnav-centered a {
  float: none;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.topnav-right {
  float: right;
}

@media screen and (max-width: 600px) {
  .topnav a, .topnav-right {
    float: none;
    display: block;
  }

  .topnav-centered a {
    position: relative;
    top: 0;
    left: 0;
    transform: none;
  }
}
</style>
</head>
<body>

<div class="topnav">

  <div class="topnav-centered">
    
  </div>

  <a href="http://localhost:8080/camagru/webcampage.php"></i> Webcam</a>
  <a href="http://localhost:8080/camagru/gallery.phtml">Gallery</a>

  <div class="topnav-right">

  <a href="http://localhost:8080/camagru/update.php">Update Details</a>
  <a href="http://localhost:8080/camagru/logout.php">Logout</a>
  

  </div>
</div>
